// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "返回服务健康状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "status\":\"ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sse/notifications": {
            "get": {
                "description": "通过 Server-Sent Events 推送实时通知",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Realtime"
                ],
                "summary": "SSE 实时通知",
                "responses": {
                    "200": {
                        "description": "event-stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ws/chat": {
            "get": {
                "description": "通过 WebSocket 进行实时双向通信",
                "tags": [
                    "Realtime"
                ],
                "summary": "WebSocket 聊天",
                "responses": {
                    "101": {
                        "description": " Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "roc_way API",
	Description:      "基于 Go + Gin 的轻量级 Web 开发框架",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
