// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/cuiyuanxin/roc_way/internal/app/admin"
	"github.com/cuiyuanxin/roc_way/internal/pkg/auth"
	"github.com/cuiyuanxin/roc_way/internal/pkg/cache"
	"github.com/cuiyuanxin/roc_way/internal/pkg/config"
	"github.com/cuiyuanxin/roc_way/internal/pkg/database"
	"github.com/cuiyuanxin/roc_way/internal/pkg/logger"
	"github.com/cuiyuanxin/roc_way/internal/pkg/realtime"
)

// Injectors from wire.go:

// InitApp 由 wire 生成，调用者通过 wire_gen.go 实际执行注入。
func InitApp(ctx context.Context, cfg config.Config) (*admin.App, func(), error) {
	loggers, err := provideLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	databaseConfig := cfg.Database
	db, err := database.Open(ctx, databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	cacheConfig := cfg.Cache
	client, err := cache.New(cacheConfig)
	if err != nil {
		return nil, nil, err
	}
	authConfig := cfg.Auth
	authAuth := auth.New(authConfig, client)
	enforcer, err := provideEnforcer(cfg)
	if err != nil {
		return nil, nil, err
	}
	hub := realtime.NewHub()
	deps := admin.Deps{
		Cfg:      cfg,
		Log:      loggers,
		DB:       db,
		Cache:    client,
		Auth:     authAuth,
		Enforcer: enforcer,
		Hub:      hub,
	}
	app := admin.NewApp(deps)
	return app, func() {
	}, nil
}

// wire.go:

// provideLogger 把 logger.Config 包装为 *logger.Loggers。
func provideLogger(cfg config.Config) (*logger.Loggers, error) {
	return logger.New(logger.Config{
		Level:  cfg.Logger.Level,
		Dir:    cfg.Logger.Dir,
		MaxMB:  cfg.Logger.MaxMB,
		Backup: cfg.Logger.Backup,
	})
}

// provideEnforcer 装配 casbin enforcer。
func provideEnforcer(cfg config.Config) (*auth.Enforcer, error) {
	return auth.NewEnforcer(cfg.Auth.ModelPath, cfg.Auth.PolicyPath)
}
