// `rocway-cli gen <kind> <name>` 渲染代码生成模板。
//
// 简单子命令内部参数解析使用标准库 flag。
package cmd

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/spf13/cobra"
)

func GenCmd() *cobra.Command {
	c := &cobra.Command{Use: "gen <kind> <name>", Short: "Generate code", Args: cobra.MinimumNArgs(2)}
	c.RunE = func(cmd *cobra.Command, args []string) error {
		kind := args[0]
		name := args[1]
		fs := flag.NewFlagSet("gen", flag.ContinueOnError)
		out := fs.String("o", "internal/app/admin", "output root")
		_ = fs.Parse(args[2:])
		return runGen(kind, name, *out)
	}
	return c
}

func runGen(kind, name, outRoot string) error {
	switch kind {
	case "controller":
		return writeTemplate(filepath.Join(outRoot, "controller", snake(name)+".go"), controllerTmpl, name)
	case "model":
		return writeTemplate(filepath.Join(outRoot, "model", snake(name)+".go"), modelTmpl, name)
	case "middleware":
		return writeTemplate(filepath.Join(outRoot, "middleware", snake(name)+".go"), middlewareTmpl, name)
	default:
		return fmt.Errorf("unknown kind: %s", kind)
	}
}

func writeTemplate(path, tmpl, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	t := template.Must(template.New("t").Parse(tmpl))
	data := struct {
		Name string
		Time string
	}{Name: name, Time: time.Now().Format(time.RFC3339)}
	return t.Execute(f, data)
}

func snake(s string) string { return strings.ToLower(s) }

const (
	controllerTmpl = `// Code generated by rocway-cli at {{.Time}}. DO NOT EDIT.
package controller

import "github.com/gin-gonic/gin"

type {{.Name}} struct{}

func New{{.Name}}() *{{.Name}} { return &{{.Name}}{} }

func (c *{{.Name}}) Register(r gin.IRouter) {
	r.GET("/{{.Name}}", c.list)
	r.POST("/{{.Name}}", c.create)
}

func (c *{{.Name}}) list(ctx *gin.Context) {}
func (c *{{.Name}}) create(ctx *gin.Context) {}
`
	modelTmpl = `// Code generated by rocway-cli at {{.Time}}. DO NOT EDIT.
package model

import "time"

type {{.Name}} struct {
	ID        uint      ` + "`gorm:\"primaryKey\" json:\"id\"`" + `
	CreatedAt time.Time ` + "`json:\"created_at\"`" + `
}

func ({{.Name}}) TableName() string { return "{{.Name}}s" }
`
	middlewareTmpl = `// Code generated by rocway-cli at {{.Time}}. DO NOT EDIT.
package middleware

import "github.com/gin-gonic/gin"

func {{.Name}}() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Next()
	}
}
`
)
